[general]
import = ["~/.config/alacritty/themes/themes/tokyo_night.toml"]

[env]
TERM = "alacritty"

[window]
opacity = 0.85

[font]
size = 12

[font.normal]
family = "IBM Plex Mono"
style = "Regular"

[font.bold]
family = "IBM Plex Mono"
style = "Bold"

[font.italic]
family = "IBM Plex Mono"
style = "Italic"

[font.bold_italic]
family = "IBM Plex Mono"
style = "Bold Italic"

[[keyboard.bindings]]
key = "Return"
mods = "Control|Shift"
action = "SpawnNewInstance"
